"""cascade delete on subject classes

Revision ID: 1d89a63f727b
Revises: c560649293d7
Create Date: 2024-12-15 22:36:36.190998

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d89a63f727b"
down_revision: Union[str, None] = "c560649293d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("classes_subject_id_fkey", "classes", type_="foreignkey")
    op.create_foreign_key(
        None, "classes", "subjects", ["subject_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "classes", type_="foreignkey")
    op.create_foreign_key(
        "classes_subject_id_fkey", "classes", "subjects", ["subject_id"], ["id"]
    )
    # ### end Alembic commands ###
