"""create chunks table

Revision ID: 350254423256
Revises: 1b6c6eb7dced
Create Date: 2024-10-30 23:08:52.732611

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector  # Add this import


# revision identifiers, used by Alembic.
revision: str = "350254423256"
down_revision: Union[str, None] = "1b6c6eb7dced"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column(
            "content_type", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True
        ),
        sa.Column("embedding", Vector(dim=1024), nullable=True),
        sa.Column(
            "top_level_section_index",
            sqlmodel.sql.sqltypes.AutoString(length=10),
            nullable=True,
        ),
        sa.Column(
            "top_level_section_title",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["section_id"], ["sections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "chunk_embedding_idx",
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_chunks_resource_id"), "chunks", ["resource_id"], unique=False
    )
    op.create_index(
        op.f("ix_chunks_section_id"), "chunks", ["section_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunks_section_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_resource_id"), table_name="chunks")
    op.drop_index(
        "chunk_embedding_idx",
        table_name="chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("chunks")
    # ### end Alembic commands ###
