"""Add new subjects to DB

Revision ID: 40ef9772ad6c
Revises: 63ac8f1e9b4c
Create Date: 2026-02-19 15:20:07.068866

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "40ef9772ad6c"
down_revision: Union[str, None] = "63ac8f1e9b4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'agriculture';")
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'agromechanics';")
    op.execute(
        "ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'animal_health_and_production';"
    )
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'arts_and_design';")
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'auto_body_repair';")
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'bible_knowledge';")
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'book_keeping';")
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'chemistry';")
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'computer_science';")
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'engineering_science';")
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'physics';")
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'acting';")
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'business_studies';")
    op.execute(
        "ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'additional_mathematics';"
    )
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'auto_electric';")
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'carpentry';")
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'civil_draughting';")
    op.execute(
        "ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'horticultural_production';"
    )
    op.execute(
        "ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'leather_goods_and_footwear';"
    )
    op.execute(
        "ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'literature_in_english';"
    )
    op.execute(
        "ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'information_and_computer_studies';"
    )
    op.execute("ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'commerce';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM subjects
        WHERE name::text IN (
            'agriculture',
            'agromechanics',
            'animal_health_and_production',
            'arts_and_design',
            'auto_body_repair',
            'bible_knowledge',
            'book_keeping',
            'chemistry',
            'computer_science',
            'engineering_science',
            'physics',
            'acting',
            'business_studies',
            'additional_mathematics',
            'auto_electric',
            'carpentry',
            'civil_draughting',
            'horticultural_production',
            'leather_goods_and_footwear',
            'literature_in_english',
            'information_and_computer_studies',
            'commerce'
        );
        """
    )

    op.execute("ALTER TYPE subjectname RENAME TO subjectname_old;")

    op.execute(
        """
        CREATE TYPE subjectname AS ENUM (
            'geography',
            'history',
            'biology',
            'english',
            'civics',
            'mathematics',
            'human_geography',
            'physical_geography'
        );
        """
    )

    op.execute(
        """
        ALTER TABLE subjects
        ALTER COLUMN name TYPE subjectname
        USING name::text::subjectname;
        """
    )

    op.execute("DROP TYPE subjectname_old;")
    # ### end Alembic commands ###
