"""add_agentic_mode_enabled_to_user

Revision ID: 8b47be6759e1
Revises: 63ac8f1e9b4c
Create Date: 2026-02-08 22:58:11.585162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b47be6759e1"
down_revision: Union[str, None] = "63ac8f1e9b4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "agentic_mode_enabled", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "agentic_mode_enabled")
    # ### end Alembic commands ###
