"""add onboarding_state field

Revision ID: c04271064481
Revises: a313a9f15106
Create Date: 2024-10-26 12:05:30.776403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c04271064481"
down_revision: Union[str, None] = "a313a9f15106"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "on_boarding_state",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
    )
    op.alter_column(
        "users",
        "state",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlmodel.sql.sqltypes.AutoString(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "state",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_column("users", "on_boarding_state")
    # ### end Alembic commands ###
