"""Added history to subjects

Revision ID: c4a17d67d125
Revises: d05f01339caa
Create Date: 2025-07-18 09:08:05.277705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c4a17d67d125'
down_revision: Union[str, None] = 'd05f01339caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'history';"
    )
    op.execute(
        "ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'biology';"
    )
    op.execute(
        "ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'english';"
    )
    op.execute(
        "ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'civics';"
    )
    op.execute(
        "ALTER TYPE subjectname ADD VALUE IF NOT EXISTS 'mathematics';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
