"""rename users on_boarding_state

Revision ID: d6b90f11242c
Revises: de4cf498c846
Create Date: 2024-11-04 22:33:29.717879

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "d6b90f11242c"
down_revision: Union[str, None] = "de4cf498c846"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "onboarding_state",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
    )
    op.drop_column("users", "on_boarding_state")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "on_boarding_state",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "onboarding_state")
    # ### end Alembic commands ###
