"""add index to subject and gradelevel in classes

Revision ID: de4cf498c846
Revises: e062b90eda73
Create Date: 2024-11-04 22:18:28.511138

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "de4cf498c846"
down_revision: Union[str, None] = "e062b90eda73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_classes_grade_level"), "classes", ["grade_level"], unique=False
    )
    op.create_index(op.f("ix_classes_subject"), "classes", ["subject"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_classes_subject"), table_name="classes")
    op.drop_index(op.f("ix_classes_grade_level"), table_name="classes")
    # ### end Alembic commands ###
