"""add gradelevels and make author optional

Revision ID: fc271252a164
Revises: 5805e9679e62
Create Date: 2024-10-29 20:32:05.974419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc271252a164'
down_revision: Union[str, None] = '5805e9679e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('grade_levels', sa.ARRAY(sa.String(length=10)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'grade_levels')
    # ### end Alembic commands ###
